var losBurritosMenu = { 'Breakfast Burritos': [
  {name: 'Burrito a La Mexicana',
    price: 6.95},
  {name: 'Bacon & Eggs Burrito',
    price: 6.95},
  {name: 'Chorizo & Eggs Burrito',
    price: 6.95},
  {name: 'Ham & Eggs Burrito',
    price: 6.95},
  {name: 'Steak & Eggs Burrito',
    price: 8.95},
  {name: 'Barbacoa & Eggs Burrito',
    price: 8.95},
  {name: 'Combination Burrito',
    price: 8.95}
], 
'Tacos': [ 
  {name: 'Carne Asada Taco',
    price: 2.75},
  {name: 'Chicken Taco',
    price: 2.75},
  {name: 'Al Pastor Taco',
    price: 2.75},
  {name: 'Carnitas Taco',
    price: 2.75},
  {name: 'Barbacoa Taco',
    price: 2.75},
  {name: 'Grilled Fish Taco',
    price: 3.25},
  {name: 'Fried Fish Taco',
    price: 3.25},
  {name: 'Shrimp Taco',
    price: 3.75},
  {name: 'Crispy Potato Taco',
    price: 2.95},
  {name: 'Crispy Taco',
    price: 2.95},
],     
'Burritos': [ 
  {name: 'Bean & Cheese Burrito',
    price: 4.95},
  {name: 'Grilled Vegetable Burrito',
    price: 6.95},
  {name: 'Carne Asada Burrito',
    price: 6.95},
  {name: 'Chicken Burrito',
    price: 6.95},
  {name: 'Barbacoa Burrito',
    price: 6.95},
  {name: 'Al Pastor Burrito',
    price: 6.95},
  {name: 'Carnitas Burrito',
    price: 6.95},
  {name: 'Green Chile Burrito',
    price: 6.95},
  {name: 'Red Chile Burrito',
    price: 6.95},
  {name: 'Combination Burrito',
    price: 8.95}, 
  {name: 'Grilled Fish Burrito',
    price: 8.95},
  {name: 'Shrimp & Scallop Burrito',
    price: 9.95},
  {name: 'California Burrito',
    price: 9.75}, ] };
